# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7330e871b91f6895f73759db8fef01194a9c702c5474b6897cf8e2fe220921ef53d44bd0b7b02977234d5d251ca416be984cd42686b459007844a095d6bb7198

test:
  secret_key_base: 9ac4de265258c92f6477b8812a3dc29c4eb82707deb0745536bdc313be8fccc6da2ff6b33e61b9eff592e559a420184d4298fabda7396d9002475fe9f3da8b4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
